import { useEffect, useState } from 'react';
import PwaShell from '../../../shared/components/PwaShell.jsx';
import { useAthleteStore } from '../athlete-store.js';
import { buildFreestyleWorkout, buildWorkoutFromRoutine } from './workout-builder.js';
import { completedSets, totalSets, transition } from './workout-model.js';
import { logSet, progress, toHistoryEntry } from './workout-logging.js';
import { elapsedSeconds, formatElapsed } from './workout-timers.js';

function StartWorkout({ onStart }) { const state = useAthleteStore(s => s.state); return <section><h1>Тренировка</h1><p className="pwa-muted">Выберите программу для начала.</p>{state.routines?.length ? <div className="workout-routines">{state.routines.map(r => <button className="pwa-card workout-choice" key={r.id} onClick={() => onStart(buildWorkoutFromRoutine(r))}><strong>{r.name}</strong><span>{r.ex?.length || 0} упражнений</span></button>)}</div> : null}<button className="pwa-button" onClick={() => onStart(buildFreestyleWorkout())}>Свободная тренировка</button></section>; }
function ActiveWorkout({ workout, onChange, onFinish, onDiscard }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const id = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(id); }, []); const p = progress(workout); const toggle = (entryIndex, setIndex) => { const entry = workout.entries[entryIndex]; const set = entry.sets[setIndex]; onChange(logSet(workout, entryIndex, setIndex, { ...set, done: !set.done })); }; return <section><div className="row-between"><div><h1>{workout.name}</h1><p className="pwa-muted">{formatElapsed(elapsedSeconds(workout.start, now))} · {p.done}/{p.total} подходов</p></div><button className="pwa-button" onClick={onDiscard}>Сбросить</button></div><div className="workout-progress"><i style={{ width: `${p.percent}%` }} /></div>{workout.entries.length ? workout.entries.map((entry, ei) => <article className="pwa-card workout-entry" key={`${entry.id}-${ei}`}><h2>{entry.title || entry.name || entry.id}</h2>{entry.sets.map((set, si) => <label className={set.done ? 'set-done' : ''} key={si}><span>Подход {si + 1}</span><span>{entry.mode === 'cardio' ? `${set.min} мин · ${set.speed} км/ч` : entry.mode === 'time' ? `${set.sec} сек` : `${set.w} кг × ${set.r}`}</span><input type="checkbox" checked={Boolean(set.done)} onChange={() => toggle(ei, si)} /></label>)}</article>) : <div className="pwa-card"><p>Добавьте упражнение в свободную тренировку через Библиотеку.</p></div>}<button className="pwa-button" disabled={!p.done} onClick={onFinish}>Завершить тренировку</button></section>; }
export function Workout() { const { state, update } = useAthleteStore(); const active = state.active; const start = workout => update({ active: workout }); const change = workout => update({ active: workout }); const finish = () => { const done = transition(active, 'finish'); update({ active: null, workouts: [...(state.workouts || []), toHistoryEntry(done)] }); }; const discard = () => { transition(active, 'discard'); update({ active: null }); }; return <PwaShell>{active ? <ActiveWorkout workout={active} onChange={change} onFinish={finish} onDiscard={discard} /> : <StartWorkout onStart={start} />}</PwaShell>; }
