export const WORKOUT_STATUS = Object.freeze({ IDLE: 'idle', ACTIVE: 'active', COMPLETED: 'completed', DISCARDED: 'discarded' });
export const SET_MODES = Object.freeze({ REPS: 'reps', TIME: 'time', CARDIO: 'cardio' });
export function modeOf(entry = {}) { return Object.values(SET_MODES).includes(entry.mode) ? entry.mode : SET_MODES.REPS; }
export function createWorkout({ id = `workout-${Date.now()}`, routineId = null, name = 'Тренировка', entries = [], now = Date.now() } = {}) { return { id, routineId, name, entries: entries.map(entry => ({ ...entry, mode: modeOf(entry), sets: (entry.sets || []).map(set => ({ ...set, done: Boolean(set.done) })) })), status: WORKOUT_STATUS.ACTIVE, start: now, cur: 0 }; }
export function totalSets(workout) { return (workout?.entries || []).reduce((total, entry) => total + (entry.sets || []).length, 0); }
export function completedSets(workout) { return (workout?.entries || []).reduce((total, entry) => total + (entry.sets || []).filter(set => set.done).length, 0); }
export function canFinish(workout) { return Boolean(workout?.entries?.length) && completedSets(workout) > 0; }
export function transition(workout, event, now = Date.now()) { if (!workout) throw new Error('workout required'); if (event === 'finish' && workout.status === WORKOUT_STATUS.ACTIVE && canFinish(workout)) return { ...workout, status: WORKOUT_STATUS.COMPLETED, end: now }; if (event === 'discard' && workout.status === WORKOUT_STATUS.ACTIVE) return { ...workout, status: WORKOUT_STATUS.DISCARDED, end: now }; if (event === 'resume' && workout.status === WORKOUT_STATUS.ACTIVE) return workout; throw new Error(`invalid workout transition: ${workout.status} -> ${event}`); }
export function toggleSet(workout, entryIndex, setIndex) { if (workout?.status !== WORKOUT_STATUS.ACTIVE) throw new Error('workout is not active'); const entries = workout.entries.map((entry, index) => index === entryIndex ? { ...entry, sets: entry.sets.map((set, i) => i === setIndex ? { ...set, done: !set.done } : set) } : entry); return { ...workout, entries }; }
